### ISSUE TITLE
Cannot find module "ngx-highlight/fill-highlight.module"

### ISSUE THREAD

**Issue by junobartowski** [arthurvaverko/ngx-highlight#5]
I ran npm install ngx-highlight --save
Then on app.module.ts:
import { HighlightModule } from 'ngx-highlight/fill-highlight.module';
inside put HighlightModule @NgModule's import but the error says: Cannot find module "ngx-highlight/fill-highlight.module"

**Comment by arthurvaverko-kaltura** [comment]
sorry need to have more info .. can you post a link to youre repo some more code folder struct? 
you using systemJS or webpack?

**Comment by junobartowski** [comment]
![ngx](https://user-images.githubusercontent.com/9026660/32052334-896ba78a-ba8a-11e7-9f1b-db7fe9940ba5.png)

I am using ionic3 framework. I checked the plugin folder and fill-highlight.module is missing. I just cant post my code right now since I removed this plugin for now. I hope you understand.

**Comment by gregduffield** [comment]
the file referred to in your readm-me fill-highlight.module does not exist!

**Comment by arthurvaverko-kaltura** [comment]
There is an error in the readme ..

Try this

mport { HighlightModule } from 'app/highlight/highlight.module'

**Comment by gregduffield** [comment]
Thanks, I did this as I saw that this was a mistake but then this leads to the new Issue that I have raised regarding the build and the typings .

**Comment by agiratech-vigneshm** [comment]
I submitted a PR fixing the ReadMe
